//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace esoftapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class demands
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public demands()
        {
            this.deals = new HashSet<deals>();
        }
    
        public int id { get; set; }
        public int client_id { get; set; }
        public int agent_id { get; set; }
        public int type_id { get; set; }
        public int address_id { get; set; }
        public string min_price { get; set; }
        public string max_price { get; set; }
        public string min_area { get; set; }
        public string max_area { get; set; }
        public string min_rooms { get; set; }
        public string max_rooms { get; set; }
        public string min_floor { get; set; }
        public string max_floor { get; set; }
    
        public virtual address address { get; set; }
        public virtual agents agents { get; set; }
        public virtual clients clients { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<deals> deals { get; set; }
        public virtual types types { get; set; }
    }
}
