//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace esoftapp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class esoftEntities : DbContext
    {
        public esoftEntities()
            : base("name=esoftEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<address> address { get; set; }
        public virtual DbSet<agents> agents { get; set; }
        public virtual DbSet<clients> clients { get; set; }
        public virtual DbSet<deals> deals { get; set; }
        public virtual DbSet<demands> demands { get; set; }
        public virtual DbSet<realestate> realestate { get; set; }
        public virtual DbSet<supplies> supplies { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<types> types { get; set; }
    }
}
