//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace esoftapp
{
    using System;
    using System.Collections.Generic;
    
    public partial class realestate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public realestate()
        {
            this.supplies = new HashSet<supplies>();
        }
    
        public int id { get; set; }
        public int typeid { get; set; }
        public int addressid { get; set; }
        public string address_house { get; set; }
        public string adress_number { get; set; }
        public Nullable<double> Coordinate_latitude { get; set; }
        public Nullable<double> Coordinate_longitude { get; set; }
        public Nullable<int> TotalArea { get; set; }
        public Nullable<int> TotalRooms { get; set; }
        public Nullable<int> Floor { get; set; }
    
        public virtual address address { get; set; }
        public virtual types types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<supplies> supplies { get; set; }
    }
}
